# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "331ba1abf3120ed4bfb3122440186c00"
name = "qr-app"
handle = "qr-app-133"
application_url = "https://indianapolis-aus-surf-pete.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-1611d013.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://indianapolis-aus-surf-pete.trycloudflare.com/auth/callback",
  "https://indianapolis-aus-surf-pete.trycloudflare.com/auth/shopify/callback",
  "https://indianapolis-aus-surf-pete.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
